# stocks api
stocks:
  api:
    fqdn: https://latest-stock-price.p.rapidapi.com
    
spring:
  profiles:
    active: prod
    jackson:
      default-property-inclusion: non_null
      
# actuators
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, mappings